### ISSUE TITLE
trying to compile it using python 3.6 but i get errors like this. please help me

### ISSUE THREAD

**Issue by Xutzgard** [apple/turicreate#1008]
src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[10:31:52] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Traceback (most recent call last):
  File "classifier.py", line 24, in <module>
    model = turi.image_classifier.create(train_data, target="animals")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 116, in create
    ptModel = _pre_trained_models.MODELS[model]()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/turicreate/toolkits/_pre_trained_models.py", line 100, in __init__
    self.mxmodel = _mx.model.load_checkpoint(_os.path.join(path, self.name), epoch)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/model.py", line 421, in load_checkpoint
    save_dict = nd.load('%s-%04d.params' % (prefix, epoch))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/ndarray/utils.py", line 175, in load
    ctypes.byref(names)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:31:52] src/ndarray/ndarray.cc:1114: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x00000001092002cf libmxnet.so + 58063
[bt] (1) 1   libmxnet.so                         0x000000010920006f libmxnet.so + 57455
[bt] (2) 2   libmxnet.so                         0x00000001091ff979 libmxnet.so + 55673
[bt] (3) 3   libmxnet.so                         0x000000010a2e1e57 MXNDListFree + 1316471
[bt] (4) 4   libmxnet.so                         0x000000010a170d21 MXNDArrayLoad + 241
[bt] (5) 5   _ctypes.cpython-36m-darwin.so       0x0000000101b12247 ffi_call_unix64 + 79
[bt] (6) 6   ???                                 0x00007ffeef172f10 0x0 + 140732909694736

**Comment by srikris** [comment]
We have a known issue (#670) on MXNet 1.2. Are you using version MXNet 1.2+?

**Comment by znation** [comment]
Closing due to inactivity; from the call stack, seems likely the same issue as #670.
