### ISSUE TITLE
Error when trying to 'import turicreate' in Google Cloud Datalab

### ISSUE THREAD

**Issue by SoroushKadineh** [apple/turicreate#1047]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-71-1b519f14fefb> in <module>()
----> 1 import turicreate

/usr/local/envs/py3env/lib/python3.5/site-packages/turicreate/__init__.py in <module>()
     17 from turicreate.version_info import __version__
     18 
---> 19 from turicreate.data_structures.sgraph import Vertex, Edge
     20 from turicreate.data_structures.sgraph import SGraph
     21 from turicreate.data_structures.sarray import SArray

/usr/local/envs/py3env/lib/python3.5/site-packages/turicreate/data_structures/__init__.py in <module>()
     16 
     17 from . import image
---> 18 from . import sframe
     19 from . import sarray
     20 from . import sgraph

/usr/local/envs/py3env/lib/python3.5/site-packages/turicreate/data_structures/sframe.py in <module>()
     14 from __future__ import division as _
     15 from __future__ import absolute_import as _
---> 16 from ..connect import main as glconnect
     17 from ..cython.cy_flexible_type import infer_type_of_list
     18 from ..cython.context import debug_trace as cython_context

/usr/local/envs/py3env/lib/python3.5/site-packages/turicreate/connect/main.py in <module>()
     11 from __future__ import absolute_import as _
     12 
---> 13 from ..cython.cy_unity import UnityGlobalProxy
     14 from ..cython.cy_server import EmbeddedServer
     15 

ImportError: libblas.so.3: cannot open shared object file: No such file or directory

----------------------------------------------------------------------------------------------------
Above is the output of when I try 'import turicreate'. I have trained a few models in Jupyter Notebook using turicreate on my local machine. But, Google Cloud Datalab is basically a cloud version of Jupyter Notebook, and I can't figure out how install 'libblas' as was suggested in #191

**Comment by TobyRoseman** [comment]
@SoroushKadineh - you need to install BLAS, as well as other Linux dependencies. See our [Linux Install Instructions](https://github.com/apple/turicreate/blob/master/LINUX_INSTALL.md) for details.

**Comment by SoroushKadineh** [comment]
@TobyRoseman I get the followings when I do `!pip install libstdc++`

> Invalid requirement: 'libstdc++'
Traceback (most recent call last):
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 7), (line:1, col:8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 253, in from_line
    req = Requirement(req)
  File "/usr/local/envs/py3env/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'++'"

**Comment by SoroushKadineh** [comment]
@TobyRoseman, `!pip install BLAS`

> Collecting BLAS
  Could not find a version that satisfies the requirement BLAS (from versions: )
  No matching distribution found for BLAS

**Comment by SoroushKadineh** [comment]
@TobyRoseman - I started everything from fresh, but I get this error: "cannot import name image" when I try to import the Turi Create.
```
! apt-get --allow-unauthenticated install -y libblas3 liblapack3 libstdc++6 python-setuptools
! apt-get --allow-unauthenticated update
! easy_install pip
! pip install virtualenv
import virtualenv as ve
ve.create_environment('venv')
cd /content/datalab/venv/bin/
!. activate	
```							

> //Note the ., which is a synonym for source

```
! pip install --upgrade pip
! pip install turicreate
! pip install turicreate==5.0b3
import turicreate as tc		
```				

> //causes -> ImportError: libblas.so.3: cannot open shared object file: No such file or directory

```
! apt-get update
! apt-get --allow-unauthenticated install gnupg	
import turicreate	
```						

> //caused -> ImportError: cannot import name image

**Comment by TobyRoseman** [comment]
`libblas3` is still not getting installed. Do you get any error messages when you execute the first cell?

Also why are you doing `apt-get --allow-unauthenticated` rather than `sudo apt-get` as the instructions say?

**Comment by SoroushKadineh** [comment]
@TobyRoseman - I use shift-enter after each command line, so by first cell you mean `! apt-get --allow-unauthenticated install -y libblas3 liblapack3 libstdc++6 python-setuptools`? 

When I use `sudo apt-get` I get the following: 

> /bin/sh: 1: sudo: not found

**Comment by TobyRoseman** [comment]
@SoroushKadineh - my guess would be you don't have permission to install system packages. 

You could try it without the `sudo` (I still don't think you need the `--allow-unauthenticated`) and see if you get an error. 

Do you know what operating system you're using? Is it Ubuntu?

**Comment by SoroushKadineh** [comment]
@TobyRoseman - when I use `! apt-get install -y libblas3 liblapack3 libstdc++6 python-setuptools` I get the following: 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libblas3
> E: Unable to locate package liblapack3
> E: Unable to locate package python-setuptools

To get rid of these errors: I do `! apt-get --allow-unauthenticated update`
Then, when I do`! apt-get install -y libblas3 liblapack3 libstdc++6 python-setuptools`, I get the following:
> WARNING: The following packages cannot be authenticated!
>   libpython2.7-minimal python2.7-minimal python-minimal mime-support
>   libpython2.7-stdlib python2.7 libpython-stdlib python libmagic1 file
>   libblas-common libblas3 libgfortran3 liblapack3 python-pkg-resources
>   python-setuptools
> E: There were unauthenticated packages and -y was used without --allow-unauthenticated

That's why I add `--allow-unauthenticated`.

I am not sure about the operating system, all I know is that I am using a VM instance via Google Cloud; namely Datalab!

**Comment by TobyRoseman** [comment]
Ok, that error message is helpful. Start a fresh notebook and make `! apt update` the first command you run. Then run `apt-get install -y libblas3 liblapack3 libstdc++6 python-setuptools`.

**Comment by TobyRoseman** [comment]
From the first error message, it looks like you need to install `gnupg`. (Seems you are probably not on Ubuntu since this package is installed by default on Ubuntu).

I would try the following:
```
! apt-get install -y gnupg
! apt update
! apt-get install -y libblas3 liblapack3 libstdc++6 python-setuptools
```

**Comment by SoroushKadineh** [comment]
@TobyRoseman - By running `! apt-get install -y gnupg` I get:
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> gnupg is already the newest version (1.4.20-1ubuntu3.2).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Then, after running the remaining mentioned commands, I get the identical results as I previously posted!!!

**Comment by TobyRoseman** [comment]
After taking another look at your output of running `apt update`, it looks like this is the root cause: `Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/ftp.us.debian.org_debian_dists_testing_InRelease`. This is likely caused by you not having permission to write to the `/var/lib/apt/lists/partial/`. You should be able to verify that is the problem by running `! ls /var/lib/apt/lists/partial/`

**Comment by SoroushKadineh** [comment]
@TobyRoseman - Yes, you're correct:

> ls: cannot access '/var/lib/apt/lists/partial/': No such file or directory

**Comment by TobyRoseman** [comment]
That error message is actually different than I expected. I expected it to say you don't have permission to list that directory but it said the directory doesn't exist. You could try to create it by running:
`! mkdir -p /var/lib/apt/lists/partial/`.

I'm guessing that will tell you that you don't have permissions.

**Comment by SoroushKadineh** [comment]
@TobyRoseman - There's no output by running: `! mkdir -p /var/lib/apt/lists/partial/`.
There's no output either by running: `! ls /var/lib/apt/lists/partial/` after running above command!

**Comment by TobyRoseman** [comment]
Interesting, looks like you where able to create the directory. Try running these two commands now:
```
! apt update
! apt-get install -y libblas3 liblapack3 libstdc++6 python-setuptools
```

**Comment by SoroushKadineh** [comment]
@TobyRoseman - same as before!!

**Comment by TobyRoseman** [comment]
I doubt the output is exactly the same. The first directory that it complains about is probably different than before.

At any rate this is not a TuriCreate Issue. The issue is that you can not install system packages in Google Cloud Datalab. I suspect because of permissions issues. I recommend that you consult documentation or support for Google Cloud Datalab, regarding how to install system packages.

**Comment by SoroushKadineh** [comment]
@TobyRoseman - I figured the issue with installing system packages! But I am getting a future warning after importing Turi Create, is that expected?

```
! chmod a+rwx /tmp
! apt update
! apt-get install -y libblas3 liblapack3 libstdc++6 python-setuptools
! easy_install pip
! pip install virtualenv
import virtualenv as ve
ve.create_environment('venv')
cd /content/datalab/venv/bin/
!. activate
! pip install --upgrade pip
! pip install turicreate
! pip install turicreate==5.0b3
import turicreate as tc 
```

> /usr/local/envs/py2env/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters

**Comment by TobyRoseman** [comment]
@SoroushKadineh - Glad you figured it out. For people looking at this issue in the future, could you share how you were able to install system packages in Google Cloud Datalab?

That warning is very common and nothing to worry about. You can safely ignore it.

**Comment by SoroushKadineh** [comment]
>  The assorted apt commands switch to a special user and then run the command.
> 
> Those commands then use the /tmp directory as part of their work, and our /tmp directory is set up so that only the root user (which is who the notebooks run as) has write permissions.
> 
> Thus, running the following in a code cell fixed the issue:

`! chmod a+rwx /tmp`

**Comment by SoroushKadineh** [comment]
@TobyRoseman - another concern is that Turi Create Visualization is not loaded at all after `dataSframe.explore() `

> Materializing SFrame

**Comment by ttpro1995** [comment]
The problem is that libblas is not install. 

`pip install -U turicreate` does not install libblas and lapack for you, so you must install it manually.

For installation using anaconda

```
conda clean --all 
conda create -n turienv python=3.6
source activate turienv
conda install -c conda-forge blas
conda install -c conda-forge lapack
pip install --no-cache-dir -U turicreate
```
