### ISSUE TITLE
iostream error during training

### ISSUE THREAD

**Issue by sejersbol** [apple/turicreate#1055]
Hi,

I'm having a problem with training an object detection model. I'm running Turi Create 5.0b3 on an EC2 p2.xlarge instance and my SFrame is 1.8 GB. At first the training goes well, but after 1150ish iterations I get the following "iostream" error:

```
$ python train.py 
Using 'image' as feature column
Using 'annotations' as annotations column
Using GPU to create model (CUDA)
Setting 'max_iterations' to 31000
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
[20:43:30] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
| 1            | 12.993       | 13.3         |
| 13           | 12.630       | 23.9         |
| 25           | 12.116       | 35.1         |
...
| 1129         | 8.502        | 1024.3       |
| 1142         | 8.537        | 1034.8       |
| 1154         | 8.592        | 1045.4       |
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    model = tc.object_detector.create(data)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 554, in create
    for batch in loader:
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 341, in next
    return self._next()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 369, in _next
    row = next(self.data_source)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 73, in next
    return self._next()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 83, in _next
    self.sframe = self.sframe.sort(_TMP_COL_RANDOM_ORDER)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 5420, in sort
    return SFrame(_proxy=self.__proxy__.sort(sort_column_names, sort_column_orders))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
IOError: Fail to write. Disk may be full.: iostream error
```

I have tried to add more disk space (100 GB EBS) and move my SFrame and training script to this bigger disk. However the bigger disk does not solve the problem - only uses about 2 GB. When I monitor the resources on the machine I see memory usage go up from around 4.6 GB to 13 GB, and GPU usage go to 0%, right before my script crashes. Also, no other filesystems run full:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             30G     0   30G   0% /dev
tmpfs           6.0G  8.6M  6.0G   1% /run
/dev/xvda1       49G   47G  2.2G  96% /
tmpfs            30G  4.1M   30G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            30G     0   30G   0% /sys/fs/cgroup
tmpfs           6.0G     0  6.0G   0% /run/user/1000
/dev/xvdf        99G  1.8G   92G   2% /turicreate
```

My training script is really simple:

```
import turicreate as tc  
 
# Load the training data  
data = tc.SFrame('training_data.sframe')  
 
# Create the Turi Create object detection model  
model = tc.object_detector.create(data)

# Save the model
model.save('project.tcmodel')
```

I'm training on about 52000 images with about 55000 bounding boxes. I have ensured that all images has reasonable sizes of around 400 x 600 pixels. Also, I create the SFrame with this simple script:

```
import turicreate as tc

# Load staging images
images = tc.load_images('staging-data')

# Load staging annotations
annotations = tc.SFrame('staging-data/annotations.csv')

# Join images and annotations 
data = images.join(annotations)

# Random split at 7:3 the data into training and test data
training_data, test_data = data.random_split(0.7)

# Save both the training and test data to disk
training_data.save('training_data.sframe')
test_data.save('test_data.sframe')
``` 

Do you have any idea of what is making my training script crash?

**Comment by sejersbol** [comment]
Hi,

So, today I tried to upgrade to Turi Create 5.0 and run my training script again. This time it all went well! After 7h 16m 34s i got a nice model with 56 classes and a mean_average_precision_50 of 0.8359. So far I'm very satisfied and the problem I was having must have been solved in the last release. Thanks!

**Comment by srikris** [comment]
Thanks for the feedback!
