### ISSUE TITLE
Unable to deploy turicreate to AWS Lambda

### ISSUE THREAD

**Issue by Cyash** [apple/turicreate#1083]
Hi! I'm having issues with deploying turicreate to AWS Lambda, I'm getting `/var/task/libstdc++.so.6: version GLIBCXX_3.4.21 not found` error, I did check your instructions at [https://github.com/apple/turicreate/blob/master/INSTALL_ISSUES.md](url), The problem is AWS Lambda runs on a AMI(name: amzn-ami-hvm-2017.03.1.20170812-x86_64-gp2) which only has GLIBCXX_3.4.19 and Amazon hasn't provided any updates for that respective AMI, I'm planning to use turicreate on Lambda only for generating predictions by loading model from S3, is there any way to mitigate this ? Any help would be appreciated! more about AWS Lambda execution environment can be found here [https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html](url)

**Comment by Cyash** [comment]
@TobyRoseman Thanks, for the response, no I wasn't able to update the AMI as its system environment is controlled by Amazon, but I was able to force the AMI to use updated libstdc++ library by setting LD_LIBRARY_PATH, but I ran into this error `: AssertionError
Traceback (most recent call last):
  File "/var/task/models.py", line 7, in predict
    import turicreate as tc
  File "/var/task/turicreate/__init__.py", line 19, in <module>
    from turicreate.data_structures.sgraph import Vertex, Edge
  File "/var/task/turicreate/data_structures/__init__.py", line 18, in <module>
    from . import sframe
  File "/var/task/turicreate/data_structures/sframe.py", line 16, in <module>
    from ..connect import main as glconnect
  File "/var/task/turicreate/connect/main.py", line 13, in <module>
    from ..cython.cy_unity import UnityGlobalProxy
  File "turicreate/cython/cy_sarray.pxd", line 92, in init turicreate.cython.cy_unity
  File "turicreate/cython/cy_model.pxd", line 28, in init turicreate.cython.cy_sarray
  File "turicreate/cython/cy_model.pyx", line 1, in init turicreate.cython.cy_model
  File "turicreate/cython/cy_sframe.pxd", line 74, in init turicreate.cython.cy_variant
  File "turicreate/cython/cy_sframe.pyx", line 1, in init turicreate.cython.cy_sframe
  File "turicreate/cython/cy_flexible_type.pyx", line 307, in init turicreate.cython.cy_flexible_type
AssertionError`  and all I'm doing in python file is simple `import turicreate`  seems like the import is failing

**Comment by TobyRoseman** [comment]
Taking a look at [that assertion](https://github.com/apple/turicreate/blob/master/src/unity/python/turicreate/cython/cy_flexible_type.pyx#L307), it seems `numpy` is not installed.

**Comment by Cyash** [comment]
@TobyRoseman thanks! I got it working !

**Comment by TobyRoseman** [comment]
Great, thanks for letting us know this is fixed.
