### ISSUE TITLE
Could not find mnist/train6k-array in Multiclass Classification example

### ISSUE THREAD

**Issue by snvkgram** [apple/turicreate#1221]
Hi

I am trying to execute the code referred in this page:  [link](https://github.com/apple/turicreate/blob/60ec6ce77a485e366ee09fbe5cf476d55a644992/userguide/supervised-learning/logistic-regression.md)

The code breaks when I execute with below error:

```

Traceback (most recent call last):
  File "multiclass_classification.py", line 4, in <module>
    data = tc.SFrame('mnist/train6k-array')
  File "/Users/ganapathiram/Documents/Ram/runtimes/turicreate/venv_turicreate/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 812, in __init__
    raise ValueError('Unknown input type: ' + format)
  File "/Users/ganapathiram/Documents/Ram/runtimes/turicreate/venv_turicreate/lib/python2.7/site-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
IOError: /Users/ganapathiram/Documents/Ram/runtimes/turicreate/mnist/train6k-array not found.
```

I have browsed to see if I can download but could not find an easy way. The python is the default one available in Mac OS.

I am executing this inside virtualenv.

Please let me know how to fix this.

Thanks
Ram

**Comment by TobyRoseman** [comment]
dup of #97
