### ISSUE TITLE
SArray.apply fails with UnpicklingError (NEWOBJ has NULL tp_new) on certain images

### ISSUE THREAD

**Issue by gustavla** [apple/turicreate#124]
This issue was identified in #114 by @res0nat0r and tracked separately here.

The clash SFrame contains a column of `tc.Image` instances.

```python
import turicreate as tc

def drop_alpha(image):
  return tc.Image(_image_data=image.pixel_data[..., :3].tobytes(),
      _width=image.width,
      _height=image.height,
      _channels=3,
      _format_enum=2,
      _image_data_size=image.width * image.height * 3)

images = tc.SFrame('clash.sframe')

images['rgb'] = images['image'].apply(drop_alpha)
```

```plain
Traceback (most recent call last):
  File "repro2.py", line 16, in <module>
    images['rgb'] = images['image'].apply(drop_alpha)
  File "/Users/larsson/.pyenv/versions/tc-4.0.0/lib/python2.7/site-packages/turicreate/data_structures/sarray.py", line 1881, in apply
    return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_na, seed))
  File "/Users/larsson/.pyenv/versions/tc-4.0.0/lib/python2.7/site-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: Runtime Exception. Exception in python callback function evaluation:
UnpicklingError('NEWOBJ class argument has NULL tp_new',):
Traceback (most recent call last):
  File "turicreate/cython/cy_pylambda_workers.pyx", line 398, in turicreate.cython.cy_pylambda_workers._init_lambda
  File "turicreate/cython/cy_pylambda_workers.pyx", line 138, in turicreate.cython.cy_pylambda_workers.lambda_evaluator.__init__
UnpicklingError: NEWOBJ class argument has NULL tp_new
```

**Comment by gustavla** [comment]
This issue is present on 4.0, however it was fixed on the master branch since updating to a newer version of cloudpickle (98e54f1fa960c08a517b95bf8571e26e8c488ef3).
