### ISSUE TITLE
OSError: /home/jovyan/photoLabel.sframe not found

### ISSUE THREAD

**Issue by davide445** [apple/turicreate#1258]
Installed docker citoki/turicreate5.1 on my Windows 10 machine.

Opened python console tyring to replicate the easy first example of image classification

```
import turicreate as tc

# Load data 
data = tc.SFrame('photoLabel.sframe')

# Create a model
model = tc.image_classifier.create(data, target='photoLabel')

# Make predictions
predictions = model.predict(data)

# Export to Core ML
model.export_coreml('MyClassifier.mlmodel')
```

I got this error

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 808, in __init__
    self.__proxy__.load_from_sframe_index(url)
  File "turicreate/cython/cy_sframe.pyx", line 71, in turicreate.cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index
  File "turicreate/cython/cy_sframe.pyx", line 74, in turicreate.cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index
OSError: /home/jovyan/photoLabel.sframe not found.

```
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 812, in __init__
    raise ValueError('Unknown input type: ' + format)
  File "/opt/conda/lib/python3.6/site-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
OSError: /home/jovyan/photoLabel.sframe not found.
>>> model = tc.image_classifier.create(data, target='photoLabel')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'data' is not defined
>>> data = tc.SFrame('photoLabel.sframe')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 808, in __init__
    self.__proxy__.load_from_sframe_index(url)
  File "turicreate/cython/cy_sframe.pyx", line 71, in turicreate.cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index
  File "turicreate/cython/cy_sframe.pyx", line 74, in turicreate.cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index
OSError: /home/jovyan/photoLabel.sframe not found.
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 812, in __init__
    raise ValueError('Unknown input type: ' + format)
  File "/opt/conda/lib/python3.6/site-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
OSError: /home/jovyan/photoLabel.sframe not found.

```

**Comment by TobyRoseman** [comment]
Hi @davide445 - 

The [example in our top level README](https://github.com/apple/turicreate#example-image-classifier-with-a-few-lines-of-code) is just intended to show how simple it can be to create an image classifier with Turi Create. The code isn't intended to be run verbatim; for that code to work you would need an SFrame called `photoLabel.sframe` in the current directory.

If you're interested in creating an image classifier, I'd recommend looking at that [section of our user guide](https://apple.github.io/turicreate/docs/userguide/image_classifier/). It contains code which can be run verbatim, assuming you have downloaded the necessary data.

It's not totally clear that the example code in our README can't be run verbatim. Let's leave this issue open until we've made that clear. I'll update the title of this issue.
