### ISSUE TITLE
Group by errors out inside lambda worker

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#1644]
The following code shows how a lambda worker calling into a groupby fails: 

```
import turicreate as tc

aggs = {"total": tc.aggregate.COUNT()}

X = tc.util.generate_random_classification_sframe(1000, "cccc", 4)
columns = [f for f in X.column_names() if f.startswith("X")]

def try_groupby(ft):
    X.groupby(ft, aggs)

all_pairs = tc.SArray([(feature, other_feature) 
                       for i, feature in enumerate(columns)
                           for j, other_feature in enumerate(columns)
                               if i < j])
# This works:
data_out = tc.SArray([try_groupby(t) for t in all_pairs])
print("Try 1:", list(data_out))

# This fails
data_out = all_pairs.apply(try_groupby)
data_out.materialize()
    
print("Try 2:", list(data_out))
```

The output of this program is: 

```
In [18]: %run test.py
('Try 1:', [None, None, None, None, None, None])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/Users/hoytak/workspace/playground/test.py in <module>()
     19 # This does not
     20 data_out = all_pairs.apply(try_groupby)
---> 21 data_out.materialize()
     22
     23 print("Try 2:", list(data_out))

/Users/hoytak/venv/lib/python2.7/site-packages/turicreate/data_structures/sarray.pyc in materialize(self)
   1300         to disk, committing all lazy evaluated operations.
   1301         """
-> 1302         return self.__materialize__()
   1303
   1304     def __materialize__(self):

/Users/hoytak/venv/lib/python2.7/site-packages/turicreate/data_structures/sarray.pyc in __materialize__(self)
   1308         """
   1309         with cython_context():
-> 1310             self.__proxy__.materialize()
   1311
   1312     def is_materialized(self):

/Users/hoytak/venv/lib/python2.7/site-packages/turicreate/cython/context.pyc in __exit__(self, exc_type, exc_value, traceback)
     47             if not self.show_cython_trace:
     48                 # To hide cython trace, we re-raise from here
---> 49                 raise exc_type(exc_value)
     50             else:
     51                 # To show the full trace, we do nothing and let exception propagate

RuntimeError: Exception in python callback function evaluation:
KeyError('Column  does not exist in SFrame',):
Traceback (most recent call last):
  File "turicreate/cython/cy_pylambda_workers.pyx", line 427, in turicreate.cython.cy_pylambda_workers._eval_lambda
  File "turicreate/cython/cy_pylambda_workers.pyx", line 170, in turicreate.cython.cy_pylambda_workers.lambda_evaluator.eval_simple
  File "/Users/hoytak/workspace/playground/test.py", line 9, in try_groupby
    X.groupby(ft, aggs)
  File "/Users/hoytak/venv/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 4201, in groupby
    raise KeyError("Column " + col + " does not exist in SFrame")
KeyError: 'Column  does not exist in SFrame'
```

**Comment by TobyRoseman** [comment]
I can reproduce this issue with TuriCreate 6.4
