### ISSUE TITLE
Possible SFrame memory corruption 

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#1708]
I’m running a few repeated jobs using Drawing Classifier toolkit to train a model from a random sample of classes from a dataset. All the jobs have the same setup configuration and allocated memory. Many of the jobs run to completion but some break down - following are examples of some of the error messages. 

I’m not able to repro the error since it happens infrequently and seems nondeterministic.  In hopes of reproing I used the same sample of classes that broke the jobs but they ran to completion on retry. The problem seems to happen when an operation `unique()` is applied on the dataset `SFrame`.

Example 1:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 92, in <module>
model = tc.drawing_classifier.create(train, 'label', validation_set = None, warm_start = ws_value)
File "/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/drawing_classifier/drawing_classifier.py", line 152, in create
classes = dataset[target].unique()
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sarray.py", line 2872, in unique
res = tmp_sf.groupby('X1',{})
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 4208, in groupby
group_ops))
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
RuntimeError: Unexpected block read failure. Bad file?
```

Example 2:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 92, in <module>
model = tc.drawing_classifier.create(train, 'label', validation_set = None, warm_start = ws_value)
File "/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/drawing_classifier/drawing_classifier.py", line 152, in create
classes = dataset[target].unique()
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sarray.py", line 2872, in unique
res = tmp_sf.groupby('X1',{})
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 4208, in groupby
group_ops))
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
MemoryError: std::bad_alloc
```

Example 3:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 74, in <module>
train = load_quickdraw_sframe(sframe_dir, current_classes, num_examples_per_class, 'train') # careful here
File "./utils/quickdraw_utils.py", line 16, in load_quickdraw_sframe
data = tc.SFrame(path)
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 812, in __init__
raise ValueError('Unknown input type: ' + format)
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
RuntimeError: No such node (archive.version)
```

Example 4:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 92, in <module>
model = tc.drawing_classifier.create(train, 'label', validation_set = None, warm_start = ws_value)
File "/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/drawing_classifier/drawing_classifier.py", line 152, in create
classes = dataset[target].unique()
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sarray.py", line 2872, in unique
res = tmp_sf.groupby('X1',{})
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 4208, in groupby
group_ops))
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
MemoryError: std::bad_alloc
```

Example 5:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 89, in <module>
model = tc.drawing_classifier.create(train, 'label', validation_set = None, warm_start = ws_value)
File "/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/drawing_classifier/drawing_classifier.py", line 152, in create
classes = dataset[target].unique()
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sarray.py", line 2872, in unique
res = tmp_sf.groupby('X1',{})
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 4208, in groupby
group_ops))
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
IOError: Cannot open s3://drawing-classifier/quickdraw/sframe/steak.sframe/m_9da514471561c7d5.0000 for read. Cannot open s3://drawing-classifier/quickdraw/sframe/steak.sframe/m_9da514471561c7d5.0000
```

Example 6:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 70, in <module>
train = load_quickdraw_sframe(sframe_dir, current_classes, num_examples_per_class, 'train') # careful here
File "./utils/quickdraw_utils.py", line 16, in load_quickdraw_sframe
data = tc.SFrame(path)
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 812, in __init__
raise ValueError('Unknown input type: ' + format)
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
RuntimeError: No such node (archive.version)
```

Example 7:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 92, in <module>
model = tc.drawing_classifier.create(train, 'label', validation_set = None, warm_start = ws_value)
File "/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/drawing_classifier/drawing_classifier.py", line 152, in create
classes = dataset[target].unique()
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sarray.py", line 2872, in unique
res = tmp_sf.groupby('X1',{})
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 4208, in groupby
group_ops))
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
IOError: Cannot open s3://drawing-classifier/quickdraw/sframe/tiger.sframe/m_3c99250b0cfd2de8.0000 for read. Cannot open s3://drawing-classifier/quickdraw/sframe/tiger.sframe/m_3c99250b0cfd2de8.0000
```

Example 8:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 92, in <module>
model = tc.drawing_classifier.create(train, 'label', validation_set = None, warm_start = ws_value)
File "/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/drawing_classifier/drawing_classifier.py", line 152, in create
classes = dataset[target].unique()
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sarray.py", line 2872, in unique
res = tmp_sf.groupby('X1',{})
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 4208, in groupby
group_ops))
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
RuntimeError: Unexpected block read failure. Bad file?
```

Example 9:
```
Traceback (most recent call last):
File "experiments/baseline_10runs_tune_topk.py", line 92, in <module>
model = tc.drawing_classifier.create(train, 'label', validation_set = None, warm_start = ws_value)
File "/usr/local/lib/python2.7/dist-packages/turicreate/toolkits/drawing_classifier/drawing_classifier.py", line 152, in create
classes = dataset[target].unique()
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sarray.py", line 2872, in unique
res = tmp_sf.groupby('X1',{})
File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 4208, in groupby
group_ops))
File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
raise exc_type(exc_value)
MemoryError: std::bad_alloc
```

The following has a different trace but may be related since when I tried to repro with the same set of classes that produced this error, it ran to completion correctly.

```
Traceback (most recent call last):
  File "experiments/baseline_10runs_tune_topk.py", line 76, in <module>
    train = load_quickdraw_sframe(sframe_dir, current_classes, num_examples_per_class, 'train') # careful here
  File "./utils/quickdraw_utils.py", line 16, in load_quickdraw_sframe
    data = tc.SFrame(path)
  File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 812, in __init__
    raise ValueError('Unknown input type: ' + format)
  File "/usr/local/lib/python2.7/dist-packages/turicreate/cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
RuntimeError: No such node (archive.version)
```

**Comment by hoytak** [comment]
Update: This appears to be related to not checking downloads -- it appears there's a failure case with the aws download routines that causes corrupted files to get through our checks.  Downloading manually using aws sync caused all the errors to go away.  Seems we need to check our downloads better !

**Comment by fareeha** [comment]
> Update: This appears to be related to not checking downloads -- it appears there's a failure case with the aws download routines that causes corrupted files to get through our checks. Downloading manually using aws sync caused all the errors to go away. Seems we need to check our downloads better !

Yes, that’s correct. Previously I was reading an SFrame from blobby bucket directly. That seemed to corrupt the SFrame somewhere in the code path. 

```
path = os.path.join(s3_bucket_url, 'apple.sframe')
data = tc.SFrame(path)
```

If I download the sframes and then read the SFrame from a local directory, it works fine:

```
# Download all sframes using `s3 sync` in a local directory
path = os.path.join(sframe_dir, 'apple.sframe')
data = tc.SFrame(path)
```

**Comment by TobyRoseman** [comment]
Is this still an issue with the latest version of TuriCreate?

**Comment by TobyRoseman** [comment]
I haven't heard back here. This was likely fixed in our S3 rewrite. I'm going to close this issue.
