### ISSUE TITLE
Unable to export ranking_factorization_recommender to CoreML

### ISSUE THREAD

**Issue by sohels** [apple/turicreate#2322]
Here's a simple example:

```
import turicreate as tc

print('Loading data...')
data = tc.SFrame.read_csv('train.csv')
print('Training model...')
model = tc.recommender.create(data, 'sender', 'account', target='action')
print('Saving model...')
model.export_coreml('recommender.mlmodel')
```

Sample data that causes the error is attached (2 line csv).
[train.csv.zip](https://github.com/apple/turicreate/files/3626235/train.csv.zip)

I see the following error when I run the above code with the attached sample data:

```
./train.py
Loading data...
Finished parsing file ./coreml/train.csv
Parsing completed. Parsed 2 lines in 0.028314 secs.
------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[str,str,int]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------
Finished parsing file ./coreml/train.csv
Parsing completed. Parsed 2 lines in 0.003939 secs.
Training model...
Preparing data set.
    Data has 2 observations with 2 users and 1 items.
    Data prepared in: 0.002575s
Training ranking_factorization_recommender for recommendations.
+--------------------------------+--------------------------------------------------+----------+
| Parameter                      | Description                                      | Value    |
+--------------------------------+--------------------------------------------------+----------+
| num_factors                    | Factor Dimension                                 | 32       |
| regularization                 | L2 Regularization on Factors                     | 1e-09    |
| solver                         | Solver used for training                         | sgd      |
| linear_regularization          | L2 Regularization on Linear Coefficients         | 1e-09    |
| ranking_regularization         | Rank-based Regularization Weight                 | 0.25     |
| max_iterations                 | Maximum Number of Iterations                     | 25       |
+--------------------------------+--------------------------------------------------+----------+
  Optimizing model using SGD; tuning step size.
  Using 2 / 2 points for tuning the step size.
+---------+-------------------+------------------------------------------+
| Attempt | Initial Step Size | Estimated Objective Value                |
+---------+-------------------+------------------------------------------+
| 0       | 25                | Not Viable                               |
| 1       | 6.25              | Not Viable                               |
| 2       | 1.5625            | No Decrease (0.877875 >= 0.250053)       |
| 3       | 0.390625          | 0.000101407                              |
| 4       | 0.195312          | 0.0142771                                |
+---------+-------------------+------------------------------------------+
| Final   | 0.390625          | 0.000101407                              |
+---------+-------------------+------------------------------------------+
Starting Optimization.
+---------+--------------+-------------------+-----------------------+-------------+
| Iter.   | Elapsed Time | Approx. Objective | Approx. Training RMSE | Step Size   |
+---------+--------------+-------------------+-----------------------+-------------+
| Initial | 77us         | 0.250053          | 0.500053              |             |
+---------+--------------+-------------------+-----------------------+-------------+
| 1       | 562us        | 0.52184           | 0.722385              | 0.390625    |
| 2       | 893us        | 0.133415          | 0.365261              | 0.232267    |
| 3       | 1.165ms      | 0.00834671        | 0.0913603             | 0.171364    |
| 4       | 1.77ms       | 0.00213152        | 0.0461684             | 0.116134    |
| 5       | 2.038ms      | 0.00100219        | 0.0316573             | 0.098237    |
| 10      | 3.35ms       | 0.000136029       | 0.0116631             | 0.0584121   |
| 21      | 6.129ms      | 1.5062e-05        | 0.00388092            | 0.0334841   |
+---------+--------------+-------------------+-----------------------+-------------+
Optimization Complete: Convergence on objective within bounds.
Computing final objective value and training RMSE.
       Final objective value: 1.22057e-05
       Final training RMSE: 0.0034936
Saving model...
This model is exported as a custom Core ML model. In order to use it in your
application, you must also include "libRecommender.dylib". For additional
details see:
https://apple.github.io/turicreate/docs/userguide/recommender/coreml-deployment.html
Traceback (most recent call last):
  File "./anaconda3/envs/coreml/lib/python3.6/site-packages/turicreate/extensions.py", line 274, in __run_class_function
    ret = self._tkclass.call_function(fnname, argument_dict)
  File "cy_model.pyx", line 35, in turicreate._cython.cy_model.UnityModel.call_function
  File "cy_model.pyx", line 40, in turicreate._cython.cy_model.UnityModel.call_function
RuntimeError: Currently, only item similarity models can be exported to Core ML (use turicreate.item_similarity.create to make such a model).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 8, in <module>
    model.export_coreml('recommender.mlmodel')
  File "./anaconda3/envs/coreml/lib/python3.6/site-packages/turicreate/toolkits/recommender/util.py", line 1830, in export_coreml
    self.__proxy__.export_to_coreml(filename)
  File "./anaconda3/envs/coreml/lib/python3.6/site-packages/turicreate/extensions.py", line 290, in <lambda>
    ret = lambda *args, **kwargs: self.__run_class_function(name, args, kwargs)
  File "./anaconda3/envs/coreml/lib/python3.6/site-packages/turicreate/extensions.py", line 277, in __run_class_function
    raise _ToolkitError(exc)
turicreate.toolkits._main.ToolkitError: Currently, only item similarity models can be exported to Core ML (use turicreate.item_similarity.create to make such a model).

Process finished with exit code 1
```

**Comment by hoytak** [comment]
Correct.  The Item similarity recommender is currently the only model that is exportable to CoreML, although we are looking into ways to make the other models exportable as well.   The main reason for this is that the other models rely heavily on user-specific data, which raises privacy concerns and model size issues when exported to an app; the item similarity method can be queried effectively using only item data and thus is better for an app.

**Comment by sohels** [comment]
@TobyRoseman @hoytak Yes, I had noticed the error message, and thanks for engaging on the correct choice of model. Since the model would be updated on-device using CoreML 3 APIs, I don't think there should be any privacy concerns. If it helps, what we're trying to do is to build some ML into our email app that observes and learns from user actions, to then automate triage to some extent. For example, if a user tends to move Github notification emails to a folder named 'Github' after reading them, but has missed doing this for a specific email, then the app should offer to do this automatically. This is just an example, we want to generalize this to capture most use cases, without the user having to manually setup rules / filters. I assumed a recommender with explicit data would be the way to go, but I'm not so sure now. Thoughts?

**Comment by hoytak** [comment]
Hey @sohels -- sorry for the delay in getting back to you here.  

I'm not sure the recommender is the way to go there -- the confidence levels required to adequately assess that sort of thing would be a bit tricky to work with.  An on-device classifier model would probably be your best bet there, but I'm not sure how best to make that work currently.  It's a use case that we're certainly thinking about however, so stay tuned.
