### ISSUE TITLE
Precision / Recall / Accuracy - Object Detector

### ISSUE THREAD

**Issue by lp55** [apple/turicreate#2338]
Hi,

   How can I get Precision / Recall / Accuracy / etc metrics for an object detector? model.evaluate only gives me mAP based ones. If I try something like this:

#test_data is the sframe created for testing the object detector. It has the same structure as the sframe used for training
predictions = model.predict(test_data)
prec = tc.evaluation.precision(test_data["annotations"], predictions, average = None)

    I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python2.7/site-packages/turicreate/toolkits/evaluation.py", line 839, in precision
    predictions, "precision", opts)
  File "/lib/python2.7/site-packages/turicreate/extensions.py", line 170, in <lambda>
    return lambda *args, **kwargs: _run_toolkit_function(fn, arguments, args, kwargs)
  File "/lib/python2.7/site-packages/turicreate/extensions.py", line 155, in _run_toolkit_function
    ret = _get_unity().run_toolkit(fnname, argument_dict)
  File "/lib/python2.7/site-packages/turicreate/_cython/context.py", line 49, in __exit__
    raise exc_type(exc_value)
TypeError: unhashable type: 'dict'

    And this does not allow me to set iou threshold for detection.
    Any ideas?

**Comment by TobyRoseman** [comment]
@lp55 - do you still get the same error using the most recent version of TuriCreate?

**Comment by lp55** [comment]
Hi, I haven't used this feature anymore as I had to build a custom metrics system from scratch to workaround this issue. I just use turicreate for training and inference now.

**Comment by TobyRoseman** [comment]
@lp55 - ok got it. This looks like more of a feature request than I originally thought. If you would be interested in contributing some of the functionality from your custom metrics system back to TuriCreate, please let me know.
