### ISSUE TITLE
Error log does not indicate TF installation required

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#2357]
On Mac, Python 2.7

If TF flag set to `True` in `activity_classifier.create()` without TF installed. The error message does not indicate that TF is missing:

```
Using CPU to create model
Traceback (most recent call last):
  File "run_ac.py", line 20, in <module>
    prediction_window=50, _advanced_parameters={'use_tensorflow':True})
  File "/Users/fareeha/temp_testing/lib/python2.7/site-packages/turicreate/toolkits/activity_classifier/_activity_classifier.py", line 196, in create
    model.train(dataset, target, session_id, validation_set, options)
  File "/Users/fareeha/temp_testing/lib/python2.7/site-packages/turicreate/extensions.py", line 290, in <lambda>
    ret = lambda *args, **kwargs: self.__run_class_function(name, args, kwargs)
  File "/Users/fareeha/temp_testing/lib/python2.7/site-packages/turicreate/extensions.py", line 277, in __run_class_function
    raise _ToolkitError(exc)
turicreate.toolkits._main.ToolkitError: An error occurred!
```

Installing TF fixes the issue

**Comment by fareeha** [comment]
Refer to #2373
