### ISSUE TITLE
AC with TF does not use GPU and breaks with ToolkitError

### ISSUE THREAD

**Issue by fareeha** [apple/turicreate#2373]
On Linux, Python 3.5

AC with TF defaults to using CPU (even when 4 GPUs available) and breaks with the following error:

```
Pre-processing 525156 samples...
Using sequences of size 1000 for model creation.
Processed a total of 43 sessions.
Using CPU to create model
Traceback (most recent call last):
  File "/task_runtime/venv/lib/python3.5/site-packages/turicreate/extensions.py", line 274, in __run_class_function
    ret = self._tkclass.call_function(fnname, argument_dict)
  File "cy_model.pyx", line 35, in turicreate._cython.cy_model.UnityModel.call_function
  File "cy_model.pyx", line 40, in turicreate._cython.cy_model.UnityModel.call_function
RuntimeError: An error occurred!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_ac_linux.py", line 89, in <module>
    prediction_window=50, _advanced_parameters={'use_tensorflow':True})
  File "/task_runtime/venv/lib/python3.5/site-packages/turicreate/toolkits/activity_classifier/_activity_classifier.py", line 196, in create
    model.train(dataset, target, session_id, validation_set, options)
  File "/task_runtime/venv/lib/python3.5/site-packages/turicreate/extensions.py", line 290, in <lambda>
    ret = lambda *args, **kwargs: self.__run_class_function(name, args, kwargs)
  File "/task_runtime/venv/lib/python3.5/site-packages/turicreate/extensions.py", line 277, in __run_class_function
    raise _ToolkitError(exc)
turicreate.toolkits._main.ToolkitError: An error occurred!
```

Disabling TF flag runs AC with the underlying GPUs.

**Comment by fareeha** [comment]
The issue happens when TF installation is missing.

Fix:
To enable running TF with CPU: `pip install tensorflow`
To run using GPU(s): `pip install tensorflow-gpu`
Checked with version 1.14.0
