### ISSUE TITLE
Classifier - add_image_features method is not defined

### ISSUE THREAD

**Issue by dhivyaaxim** [apple/turicreate#2401]
@znation @TobyRoseman  add_image_features method is not defined

**Error:**
import turicreate as tc
 images = tc.image_analysis.load_images("/home/aximsoft/Desktop/images")
 images = tc.image_classifier.annotate(images)
[15:54:15] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[15:54:15] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aximsoft/.local/lib/python2.7/site-packages/turicreate/toolkits/image_classifier/_annotate.py", line 118, in annotate
    annotation_window.add_image_features(feature_sframe)
  File "/home/aximsoft/.local/lib/python2.7/site-packages/turicreate/extensions.py", line 299, in __getattr__
    raise AttributeError("no attribute " + name)
AttributeError: no attribute add_image_features

**Comment by syoutsey** [comment]
@dhivyaaxim what version of Turi Create and OS are you using? I'm unable to reproduce this error with Turi Create 5.8, Python 2.7 (as above), on macOS 10.15.1.

**Comment by srikris** [comment]
I am able to reproduce this on Linux. @znation @abhishekpratapa Is this feature expected to work on Linux also? The documentation doesn't say it's Mac only.

**Comment by znation** [comment]
I think it is expected to work on Linux too. I'll investigate.
