### ISSUE TITLE
Error calling TCMPSReadFloatArray

### ISSUE THREAD

**Issue by tidbeck** [apple/turicreate#2600]
**Hardware:**
MacBook Pro (Retina, Mid 2012)
2,3 GHz, 8GB, Geforce GT 650M

**Software version:**
macOS Catalina 10.15.1
Python 3.7.4
turicreate 5.8

**Steps to reproduce**
```
import turicreate as tc
data =  tc.SFrame('cats.sframe')
train_data, test_data = data.random_split(0.8)
model = tc.object_detector.create(train_data)
```

**Result**
```
▶ python3 Train.py
+--------------------------+-------------------------------+
|          image           |          annotations          |
+--------------------------+-------------------------------+
| Height: 1500 Width: 843  | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 843  | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 1125 | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 1125 | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 1125 | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 1125 | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 1125 | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 1125 | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 1125 | [{'label': 'cat', 'coordin... |
| Height: 1500 Width: 1125 | [{'label': 'cat', 'coordin... |
+--------------------------+-------------------------------+
[49 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.
Using 'image' as feature column
Using 'annotations' as annotations column
Setting 'batch_size' to 16
Using GPU to create model (NVIDIA GeForce GT 650M)
Setting 'max_iterations' to 2000
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 4.985        | 19.0         |
...
...
...
| 936          | 1.256        | 6111.2       |
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error: 
	(null)
	Internal Error (IOAF code 1)
	<NVMTLCommandBuffer: 0x7fa731dc2e50>
    label = <none> 
    device = <NVMTLDevice: 0x1196da000>
        name = NVIDIA GeForce GT 650M 
    commandQueue = <NVMTLCommandQueue: 0x7fa72bb9c7b0>
        label = <none> 
        device = <NVMTLDevice: 0x1196da000>
            name = NVIDIA GeForce GT 650M 
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error: 
	(null)
	Invalid Resource (IOAF code 9)
	<NVMTLCommandBuffer: 0x7fa72d934420>
    label = <none> 
    device = <NVMTLDevice: 0x1196da000>
        name = NVIDIA GeForce GT 650M 
    commandQueue = <NVMTLCommandQueue: 0x7fa72bb9c7b0>
        label = <none> 
        device = <NVMTLDevice: 0x1196da000>
            name = NVIDIA GeForce GT 650M 
    retainedReferences = 1
2019-11-10 22:00:36.033 Python[57579:1102974] Error
Traceback (most recent call last):
  File "Train.py", line 11, in <module>
    model = tc.object_detector.create(train_data)
  File "/usr/local/lib/python3.7/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 699, in create
    cur_loss = wait_for_batch()
  File "/usr/local/lib/python3.7/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 680, in wait_for_batch
    batch_loss = pending_loss.asnumpy()  # Waits for the batch to finish
  File "/usr/local/lib/python3.7/site-packages/turicreate/toolkits/_mps_utils.py", line 347, in asnumpy
    assert status_code == 0, "Error calling TCMPSReadFloatArray"
AssertionError: Error calling TCMPSReadFloatArray
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1308, in _shutdown
    lock.acquire()
```

**Comment by TobyRoseman** [comment]
@tidbeck - Thanks for reporting this issue. Do you always get this error or is the issue intermittent?

**Comment by tidbeck** [comment]
@TobyRoseman I tried three or four times and got it every time but not on the same iteration.

**Comment by TobyRoseman** [comment]
@tidbeck - Are you still seeing this behavior with TuriCreate 6.1?

**Comment by tidbeck** [comment]
@TobyRoseman unfortunately the battery on that computer gave up so I'm not able to test it. Guess you can close this issue.
