### ISSUE TITLE
Opening SFrame.read_csv from S3 bucket

### ISSUE THREAD

**Issue by Ridingst** [apple/turicreate#2617]
Hi All,

Very similar to #2278 but adding the region doesn't resolve.

I'm trying to load from a private S3 bucket (running locally with minio hence the localhost endpoint).

In the following code I can load the data into the pandas df (via s3fs) without issue however I get "No files corresponding to the specified path" error within turicreate.

Any help would be greatly appreciated. Let me know if anymore information is needed.

```import os
import turicreate as tc
import pandas as pd
from s3fs.core import S3FileSystem

os.environ['AWS_ACCESS_KEY_ID'] = access
os.environ['AWS_SECRET_ACCESS_KEY'] = secret

tc.config.set_runtime_config('TURI_S3_REGION', 'us-east-1')
tc.config.set_runtime_config('TURI_FILEIO_INSECURE_SSL_CERTIFICATE_CHECKS', 1)
tc.config.set_runtime_config('TURI_S3_ENDPOINT', 'http://localhost:9000')

s3 = S3FileSystem(
    anon=False,
    client_kwargs={
        'endpoint_url':'http://localhost:9000',
        'aws_access_key_id':access,
        'aws_secret_access_key':secret
    })
location = 'pipeline-output/profiles_20191007.csv'


df = pd.read_csv(s3.open(location))
sf = tc.SFrame.read_csv('s3://pipeline-output/profiles_20191007.csv')

df.head()
sf.head()
```

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1041             with cython_context():
-> 1042                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1043         except Exception as e:

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

OSError: No files corresponding to the specified path (s3://pipeline-output/profiles_20191007.csv).

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-3-6f23e4ce07d4> in <module>()
----> 1 tc.SFrame.read_csv('s3://pipeline-output/profiles_20191007.csv')

~/.local/lib/python3.5/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1511                                   false_values=false_values,
   1512                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1513                                   **kwargs)[0]
   1514 
   1515 

~/.local/lib/python3.5/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
    974                                  true_values=true_values,
    975                                  false_values=false_values,
--> 976                                  _only_raw_string_substitutions=_only_raw_string_substitutions)
    977                 column_type_hints = SFrame._infer_column_types_from_lines(first_rows)
    978                 typelist = '[' + ','.join(t.__name__ for t in column_type_hints) + ']'

~/.local/lib/python3.5/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1511                                   false_values=false_values,
   1512                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1513                                   **kwargs)[0]
   1514 
   1515 

~/.local/lib/python3.5/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1040                 glconnect.get_server().set_log_progress(False)
   1041             with cython_context():
-> 1042                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1043         except Exception as e:
   1044             if type(e) == RuntimeError and "CSV parsing cancelled" in str(e.args[0]):

~/.local/lib/python3.5/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     47             if not self.show_cython_trace:
     48                 # To hide cython trace, we re-raise from here
---> 49                 raise exc_type(exc_value)
     50             else:
     51                 # To show the full trace, we do nothing and let exception propagate

OSError: No files corresponding to the specified path (s3://pipeline-output/profiles_20191007.csv)
```

**Comment by syoutsey** [comment]
Hi @Ridingst, I noticed that the filepath to `read_csv` differs in your usage of Pandas and Turi Create. What happens if you use the `s3://` prefix as mentioned in the [Pandas docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)?

**Comment by Ridingst** [comment]
Thanks for the prompt response.

When running the pandas `read_csv` with `s3://` as a prefix it doesn't seem to pickup the endpoint url correctly. Hence why I instantiated S3FileSystem with `endpoint_url`. AFAIK there is no way to specify an endpoint when calling `read_csv` within pandas and I'm using the solution [described here](https://stackoverflow.com/questions/35803601/reading-a-file-from-a-private-s3-bucket-to-a-pandas-dataframe/43838676) in the test scenario.

If I pass the instantiated `S3FileSystem` to `tc.SFrame.read_csv` then I get the following error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-15006b32adde> in <module>()
----> 1 sf_2 = tc.SFrame.read_csv(s3.open(location))

~/.local/lib/python3.5/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1511                                   false_values=false_values,
   1512                                   _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1513                                   **kwargs)[0]
   1514 
   1515 

~/.local/lib/python3.5/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
    950 
    951         proxy = UnitySFrameProxy()
--> 952         internal_url = _make_internal_url(url)
    953 
    954         # Attempt to automatically detect the column types. Either produce a

~/.local/lib/python3.5/site-packages/turicreate/util/__init__.py in _make_internal_url(url)
    123 
    124     # Convert Windows paths to Unix-style slashes
--> 125     url = _convert_slashes(url)
    126 
    127     # Try to split the url into (protocol, path).

~/.local/lib/python3.5/site-packages/turicreate/util/__init__.py in _convert_slashes(path)
     36     Converts all windows-style slashes to unix-style slashes
     37     """
---> 38     return path.replace('\\', '/')
     39 
     40 def _get_s3_endpoint():

AttributeError: 'S3File' object has no attribute 'replace'
```

**Comment by Ridingst** [comment]
I've recreated this issue with a minimal setup in this repo: https://github.com/Ridingst/turicreate-bug-example

The script located in `/turicreate/script.py` contains the following;

```import os
import turicreate as tc
import pandas as pd
from s3fs.core import S3FileSystem

import time
time.sleep(5) # Hacky way of avoiding having to check if the buckets have been created by docker.

os.environ['AWS_ACCESS_KEY_ID'] = 'minio'
os.environ['AWS_SECRET_ACCESS_KEY'] = 'minio123'
os.environ['AWS_S3_ENDPOINT'] = 'http://minio:9000'

tc.config.set_runtime_config('TURI_S3_REGION', 'us-east-1')
tc.config.set_runtime_config('TURI_FILEIO_INSECURE_SSL_CERTIFICATE_CHECKS', 1)
tc.config.set_runtime_config('TURI_S3_ENDPOINT', 'http://minio:9000')

s3 = S3FileSystem(
    anon=False,
    client_kwargs={
        'endpoint_url':'http://minio:9000',
        'aws_access_key_id':'minio',
        'aws_secret_access_key':'minio123'
    })
location = 'output/sample.csv'

# This doesn't work because pandas can't read a private bucket
#df = pd.read_csv('s3://output/sample.csv')

# This does work as S3FileSystem is correctly configured for a private bucket
print('First getting the csv using S3FileSystem, and pandas...')
try:
    df = pd.read_csv(s3.open(location))
    print(df)
    print('Success')
except:
    print('ERROR: Couldnt get from S3 using pandas')
    raise


# This doesn't work and will error out despite the turicreate being configured to use the same parameters
print('\nNow try and get the same csv using Turicreate...')
try:
    sf = tc.SFrame.read_csv('s3://output/sample.csv')
    sf.print_rows()
    print('Success getting from S3 using Turicreate')
except:
    print('ERROR getting from S3 using turicreate')
    raise```


Using `docker-compose up` I get the following logs;

```
turicreate_1         | First getting the csv using S3FileSystem, and pandas...
turicreate_1         |    col1  col2  col3
turicreate_1         | 0  val1  val2  val3
turicreate_1         | 1  val4  val5  val6
turicreate_1         | Success
turicreate_1         | 
turicreate_1         | Now try and get the same csv using Turicreate...
turicreate_1         | ERROR getting from S3 using turicreate
turicreate_1         | Traceback (most recent call last):
turicreate_1         |   File "/usr/local/script.py", line 43, in <module>
turicreate_1         |     sf = tc.SFrame.read_csv('s3://output/sample.csv')
turicreate_1         |   File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 1513, in read_csv
turicreate_1         |     **kwargs)[0]
turicreate_1         |   File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 976, in _read_csv_impl
turicreate_1         |     _only_raw_string_substitutions=_only_raw_string_substitutions)
turicreate_1         |   File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 1513, in read_csv
turicreate_1         |     **kwargs)[0]
turicreate_1         |   File "/usr/local/lib/python2.7/dist-packages/turicreate/data_structures/sframe.py", line 1042, in _read_csv_impl
turicreate_1         |     errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
turicreate_1         |   File "/usr/local/lib/python2.7/dist-packages/turicreate/_cython/context.py", line 49, in __exit__
turicreate_1         |     raise exc_type(exc_value)
turicreate_1         | IOError: No files corresponding to the specified path (s3://output/sample.csv).
turicreate-bug-report_turicreate_1 exited with code 1
```

Feel free to clone [the repo](https://github.com/Ridingst/turicreate-bug-example) and run for yourself.

**Comment by syoutsey** [comment]
@Ridingst I think I see what's going on here. `s3fs.open()` returns a Python `File` object, which Pandas can read. Turi Create requires that the argument to `read_csv` be a string to a file on disk or on S3 (among other sources), which is incompatible with the existing `s3fs` API.

A workaround would be for your script to first get the file from `s3fs`, save it to disk, then read it with `read_csv`. This is obviously non-optimal from both a performance and code cleanliness perspective, but until `read_csv` supports reading from a Python `File` object (and the [existing S3 bug](https://github.com/apple/turicreate/issues/2278) is fixed) this may be your best bet.

I'll open (or find) an issue related to instantiating SFrames from a File object.

Thanks for bringing this to our attention.

**Comment by philmassie** [comment]
Apologies for bringing this back to life, I'm having the same issue and cant quite figure it out.
Id be very grateful for any assistance, I'm trying to get data from PySpark into Turi, and it seems that multipart csv is the most direct route.

Python 3.7
TuriCreate 6.4.1
EC2 to S3 in same account, same region

```
csv_bucket = "my_bucket"
csv_key = "path/to/my/csv_file.csv"

# Pandas test
s3 = S3FileSystem(anon=False)
pdf = pd.read_csv(s3.open(f"{csv_bucket}/{csv_key}", mode="rb"))

# Sframe test
sts_client = boto3.client('sts')
assumed_role_object=sts_client.assume_role(
    RoleArn="arn:aws:iam::123:role/my-ec2-role",
    RoleSessionName="AssumeRoleSession1"
)

os.environ["AWS_ACCESS_KEY_ID"] = assumed_role_object["Credentials"]["AccessKeyId"]
os.environ["AWS_SECRET_ACCESS_KEY"] = assumed_role_object["Credentials"]["SecretAccessKey"]
os.environ["AWS_SESSION_TOKEN"] = assumed_role_object["Credentials"]["SessionToken"]

tc.config.set_runtime_config("TURI_FILEIO_INSECURE_SSL_CERTIFICATE_CHECKS", 1)
tc.config.set_runtime_config("TURI_S3_REGION","eu-west-1")
tc.config.set_runtime_config("TURI_S3_ENDPOINT", "https://s3.eu-west-1.amazonaws.com")

sfdf = tc.SFrame.read_csv(f"s3://{csv_bucket}/{csv_key}")
```
Error:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda3/envs/py37_emr_test/lib/python3.7/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1093             with cython_context():
-> 1094                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1095         except Exception as e:

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_csvs()

OSError: No files corresponding to the specified path (s3://my_bucket/path/to/my/csv_file.csv).

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
~/codebase/recommendation_engines/03_turicreate/mvp/02_data_prep.py in <module>
     26 tc.config.set_runtime_config("TURI_S3_REGION","eu-west-1")
     27 tc.config.set_runtime_config("TURI_S3_ENDPOINT", "https://s3.eu-west-1.amazonaws.com")
---> 28 sfdf = tc.SFrame.read_csv(f"s3://{csv_bucket}/{csv_key}")

~/anaconda3/envs/py37_emr_test/lib/python3.7/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1576             false_values=false_values,
   1577             _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1578             **kwargs
   1579         )[0]
   1580 

~/anaconda3/envs/py37_emr_test/lib/python3.7/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1002                     true_values=true_values,
   1003                     false_values=false_values,
-> 1004                     _only_raw_string_substitutions=_only_raw_string_substitutions,
   1005                 )
   1006                 column_type_hints = SFrame._infer_column_types_from_lines(first_rows)

~/anaconda3/envs/py37_emr_test/lib/python3.7/site-packages/turicreate/data_structures/sframe.py in read_csv(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1576             false_values=false_values,
   1577             _only_raw_string_substitutions=_only_raw_string_substitutions,
-> 1578             **kwargs
   1579         )[0]
   1580 

~/anaconda3/envs/py37_emr_test/lib/python3.7/site-packages/turicreate/data_structures/sframe.py in _read_csv_impl(cls, url, delimiter, header, error_bad_lines, comment_char, escape_char, double_quote, quote_char, skip_initial_space, column_type_hints, na_values, line_terminator, usecols, nrows, skiprows, verbose, store_errors, nrows_to_infer, true_values, false_values, _only_raw_string_substitutions, **kwargs)
   1092                 glconnect.get_server().set_log_progress(False)
   1093             with cython_context():
-> 1094                 errors = proxy.load_from_csvs(internal_url, parsing_config, type_hints)
   1095         except Exception as e:
   1096             if type(e) == RuntimeError and "CSV parsing cancelled" in str(e.args[0]):

~/anaconda3/envs/py37_emr_test/lib/python3.7/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     48             if not self.show_cython_trace:
     49                 # To hide cython trace, we re-raise from here
---> 50                 raise exc_type(exc_value)
     51             else:
     52                 # To show the full trace, we do nothing and let exception propagate
OSError: No files corresponding to the specified path (s3://my_bucket/path/to/my/csv_file.csv).
```
