### ISSUE TITLE
6.0 toolkits doesn't have model.name() function

### ISSUE THREAD

**Issue by jakesabathia2** [apple/turicreate#2763]
```
model = tc.object_detector.create(data)
print(model.name())
```
results in
```
Traceback (most recent call last):
  File "OD Test Cases.py", line 66, in <module>
    print(model.name())
  File "/Users/henry/Desktop/turicreate/release/src/python/turicreate/toolkits/_model.py", line 397, in __getattribute__
    return object.__getattribute__(self, attr)
AttributeError: 'ObjectDetector' object has no attribute 'name'
```

**Comment by jakesabathia2** [comment]
hmmm turns out all toolkit don't have this function yet.

**Comment by srikris** [comment]
We should not fix this. It's not pythonic to add a function.
