### ISSUE TITLE
sound classifier model cannot be used in lambda function

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#2776]
Trying to apply a sound classifier model in a lambda function caused an error on capture: 

```
In [17]: test_set["pred_prob"] = test_set["pred_prob"].apply(lambda v: dict(zip(model.classes, v)))
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:root:TensorFlow version 2.0.0 detected. Last version known to be fully compatible is 1.13.1 .
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/hoytak/venv/local/lib/python2.7/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-6d25e95fb763> in <module>()
----> 1 test_set["pred_prob"] = test_set["pred_prob"].apply(lambda v: dict(zip(model.classes, v)))

/home/hoytak/venv/local/lib/python2.7/site-packages/turicreate/data_structures/sarray.pyc in apply(self, fn, dtype, skip_na)
   1860
   1861         with cython_context():
-> 1862             return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_na, seed))
   1863
   1864

/home/hoytak/venv/local/lib/python2.7/site-packages/turicreate/_cython/context.pyc in __exit__(self, exc_type, exc_value, traceback)
     47             if not self.show_cython_trace:
     48                 # To hide cython trace, we re-raise from here
---> 49                 raise exc_type(exc_value)
     50             else:
     51                 # To show the full trace, we do nothing and let exception propagate

RuntimeError: Runtime Exception. Exception in python callback function evaluation:
EOFError():
Traceback (most recent call last):
  File "cy_pylambda_workers.pyx", line 394, in turicreate._cython.cy_pylambda_workers._init_lambda
  File "cy_pylambda_workers.pyx", line 134, in turicreate._cython.cy_pylambda_workers.lambda_evaluator.__init__
EOFError
```

(python 2.7)

Note: this also holds in 5.8.

**Comment by TobyRoseman** [comment]
@hoytak - isn't this the case with all of our models? I also can't do this with logistic regression, although I get a different error message.

**Comment by hoytak** [comment]
It used to be supported and tested a long time ago, but seems something changed with the python toolkit classes to make it not possible.  Interesting.

**Comment by getsanjeevdubey** [comment]
@hoytak  @TobyRoseman  Were you able to find any solution?
I am doing a similar thing, 
sf['col2'] = sf['col'].apply(lambda x: model.get_tags(x))
model here is a flair based bert-model used to get class of a sentence classifier.
It just keeps on running, doesnot return any result, or throw any error.
