### ISSUE TITLE
Master fails OD training on the GPU

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#2821]
```
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
Traceback (most recent call last):
  File "/task_runtime/venv/lib/python3.5/site-packages/turicreate/extensions.py", line 274, in __run_class_function
    ret = self._tkclass.call_function(fnname, argument_dict)
  File "cy_model.pyx", line 35, in turicreate._cython.cy_model.UnityModel.call_function
  File "cy_model.pyx", line 40, in turicreate._cython.cy_model.UnityModel.call_function
RuntimeError: An error occurred: RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().
```

**Comment by syoutsey** [comment]
Dupe of: https://github.com/apple/turicreate/issues/2802
