### ISSUE TITLE
Error In installing turicreate

### ISSUE THREAD

**Issue by AJKBajwa** [apple/turicreate#2858]
Whenever I run the following command:
```
pip install -U turicreate
```

in my anaconda virtual environment, I get the following error:

 Using cached https://files.pythonhosted.org/packages/96/19/44edfc07bd1b03596578ff02d9727b83c2ae50ee969ce2ab23724009d9ff/turicreate-5.7.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/aj-khalid/anaconda3/envs/gl-env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8lqpx2f4/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8lqpx2f4/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8lqpx2f4/turicreate/pip-egg-info
         cwd: /tmp/pip-install-8lqpx2f4/turicreate/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/aj-khalid/anaconda3/envs/gl-env/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-8lqpx2f4/turicreate/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Please, help. 
Thank you.

**Comment by AJKBajwa** [comment]
Needed python version 3.6
