### ISSUE TITLE
Current S3 file system code path doesn't use Aws SigV4

### ISSUE THREAD

**Issue by guihao-liang** [apple/turicreate#2910]
Related to #2278.

The `s3 region` can be set in the sigv4 auth body to find the right IAM to do the auth. We set s3 region by `TURI_S3_REGION` but the underlying code path doesn't pass the region info to s3.

**Comment by guihao-liang** [comment]
repro,

```
import turicreate as tc
tc.config.set_runtime_config("TURI_S3_REGION", "blobby")
tc.config.set_runtime_config("TURI_S3_ENDPOINT", "https://blob.mr3.simcloud.apple.com")
sf = tc.SFrame('s3://model-ideation-dev/image-classification/data/transfer-learning/sframes/v2_train_food.sframe')

Traceback (most recent call last):
  File "call.py", line 7, in <module>
    sf = tc.SFrame('s3://model-ideation-dev/image-classification/data/transfer-learning/sframes/v2_train_food.sframe')
  File "/Users/guihaoliang/Work/gui-2-36/debug/src/python/turicreate/data_structures/sframe.py", line 809, in __init__
    self.__proxy__.load_from_sframe_index(url)
  File "cy_sframe.pyx", line 71, in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index
  File "cy_sframe.pyx", line 74, in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index
OSError: s3://model-ideation-dev/image-classification/data/transfer-learning/sframes/v2_train_food.sframe not found. ErrMsg: ('bucket: 'model-ideation-dev', object_name: 'image-classification/data/transfer-learning/sframes/v2_train_food.sframe', endpoint: '', proxy: '', region: 'blobby') Error while performing ListObjects. Error Name: XML_ERROR_PARSING_TEXT. Error Message: Unable to parse ExceptionName: XML_ERROR_PARSING_TEXT Message: Unable to generate a proper httpResponse from the response stream.   Response code: 401 in ../src/core/storage/fileio/s3_api.cpp at 392
. operator() from ../src/core/storage/sframe_interface/unity_sframe.cpp at 120
```
