### ISSUE TITLE
Vague Error When Doing SFrame.save(...)

### ISSUE THREAD

**Issue by nseidl** [apple/turicreate#3242]
When trying to save an SFrame to a directory that does not exist, this exception gets thrown. It would be nice if there were more detail to make the specific problem more obvious to the user.

```
Traceback (most recent call last):
  File "/Users/user/anaconda3/envs/py36/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 3036, in save
    self.__proxy__.save(url)
  File "cy_sframe.pyx", line 87, in turicreate._cython.cy_sframe.UnitySFrameProxy.save
  File "cy_sframe.pyx", line 90, in turicreate._cython.cy_sframe.UnitySFrameProxy.save
OSError: No such file or directory
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/user/cvml-data-team/collection_projects/gurn-lb/create_split.py", line 10, in <module>
    split_uploader.build_trove_object()
  File "/Users/user/cvml-data-team/tools/trove/trove_uploader.py", line 685, in build_trove_object
    self.save_sframes_locally(sframes)
  File "/Users/user/cvml-data-team/tools/trove/trove_uploader.py", line 668, in save_sframes_locally
    sframe.save(save_path)
  File "/Users/user/anaconda3/envs/py36/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 3043, in save
    raise ValueError("Unsupported format: {}".format(format))
  File "/Users/user/anaconda3/envs/py36/lib/python3.6/site-packages/turicreate/_cython/context.py", line 50, in __exit__
    raise exc_type(exc_value)
OSError: No such file or directory
```

**Comment by TobyRoseman** [comment]
I'm not able to reproduce this issue. The following code works:
```python
import turicreate as tc
sf = tc.SFrame({'a': range(10)})
sf.save('/tmp/this/folder/does/not/exist')
```
It creates the directory structure and save the SFrame there.

@nseidl - please provide some simple, standalone code to reproduce the issue.

**Comment by nseidl** [comment]
This fails, as expected, because /a does not exist. But, the error could be slightly more descriptive, such as "the directory where you'd like to save the sframe does not exist, or you don't have permission to create it"

import turicreate as tc
sf = tc.SFrame({'a': range(10)})
sf.save('/a/b/c')

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/py36/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 3062, in save
    self.__proxy__.save(url)
  File "cy_sframe.pyx", line 87, in turicreate._cython.cy_sframe.UnitySFrameProxy.save
  File "cy_sframe.pyx", line 90, in turicreate._cython.cy_sframe.UnitySFrameProxy.save
OSError: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/py36/lib/python3.6/site-packages/turicreate/data_structures/sframe.py", line 3069, in save
    raise ValueError("Unsupported format: {}".format(format))
  File "/usr/local/anaconda3/envs/py36/lib/python3.6/site-packages/turicreate/_cython/context.py", line 50, in __exit__
    raise exc_type(exc_value)
OSError: No such file or directory

**Comment by TobyRoseman** [comment]
Surprisingly, the error message is not actually generated by TuriCreate. It's generate by [`std::strerror`](https://github.com/apple/turicreate/blob/01c23080e5934c0bc11c1c89e7fa73fe93a3e3c4/src/core/logging/logger.hpp#L429). There might be some more going on here. We probably don't want to just blindly change the error message.
