### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'channels'

### ISSUE THREAD

**Issue by waheed0332** [apple/turicreate#3331]
I'm facing a NoneType error when my training reaches 4018 iterations.

Traceback (most recent call last):
  File "train.py", line 8, in <module>
    model = tc.object_detector.create(train, grid_shape = [20, 20], random_seed = 42)
  File "/media/alizaa/DATA 1/Turi_create_21-09-20/turi-env/lib/python3.6/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 571, in create
    for batch in loader:
  File "/media/alizaa/DATA 1/Turi_create_21-09-20/turi-env/lib/python3.6/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 338, in __next__
    return self._next()
  File "/media/alizaa/DATA 1/Turi_create_21-09-20/turi-env/lib/python3.6/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 369, in _next
    row = next(self.data_source)
  File "/media/alizaa/DATA 1/Turi_create_21-09-20/turi-env/lib/python3.6/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 66, in __next__
    return self._next()
  File "/media/alizaa/DATA 1/Turi_create_21-09-20/turi-env/lib/python3.6/site-packages/turicreate/toolkits/object_detector/_sframe_loader.py", line 86, in _next
    if turi_image.channels!=3:
AttributeError: 'NoneType' object has no attribute 'channels'

**Comment by TobyRoseman** [comment]
@waheed0332 - since you closed this issue, I'm assuming you figured out the problem. It doesn't look like you're using the most recent version of TuriCreate. I recommend updating to the latest version.
