### ISSUE TITLE
SHMIPC Permission denied: error(13) = Permission Denied

### ISSUE THREAD

**Issue by mxlei01** [apple/turicreate#3361]
I recently upgraded to Big Sur, and it seems that the Turicreate library does not work anymore

```
>>> import turicreate as tc
>>> tc.SFrame([1, 2, 3])
Columns:
	X1	int

Rows: 3

Data:
+----+
| X1 |
+----+
| 1  |
| 2  |
| 3  |
+----+
[3 rows x 1 columns]

>>> a = tc.SFrame([1, 2, 3])
>>> a["X1"].apply(lambda x: x+1)
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (bind:140): SHMIPC initialization Error (2), stage 2: Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): async_reply_socket construction: : Unexpected socket error(13) = Permission denied
1605490759 : ERROR:    (print_zmq_error:17): publish_socket construction: : Unexpected socket error(13) = Permission denied
Traceback (most recent call last):
  File "/Users/maxlei/.pyenv/versions/377/lib/python3.7/site-packages/turicreate/data_structures/sarray.py", line 1947, in apply
    return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_na, seed))
  File "cy_sarray.pyx", line 130, in turicreate._cython.cy_sarray.UnitySArrayProxy.transform
  File "cy_sarray.pyx", line 141, in turicreate._cython.cy_sarray.UnitySArrayProxy.transform
RuntimeError: Cannot evaluate lambda. No Lambda workers have been successfully started.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maxlei/.pyenv/versions/377/lib/python3.7/site-packages/turicreate/data_structures/sarray.py", line 1947, in apply
    return SArray(_proxy=self.__proxy__.transform(fn, dtype, skip_na, seed))
  File "/Users/maxlei/.pyenv/versions/377/lib/python3.7/site-packages/turicreate/_cython/context.py", line 50, in __exit__
    raise exc_type(exc_value)
RuntimeError: Cannot evaluate lambda. No Lambda workers have been successfully started.
```

**Comment by mxlei01** [comment]
Disabling SIP on Macs or adding `chmod -R 777 /tmp` fixes the issue.
