### ISSUE TITLE
style transfer with batch_size>1 exception

### ISSUE THREAD

**Issue by Vozf** [apple/turicreate#3376]
I try to use style transfer and set batch_size to 2. This results in error
model = tc.style_transfer.create(styles, content, batch_size=2)
```
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
Traceback (most recent call last):
  File "/home/a_yaroshevich/projects/pixomatic/pixomatic_dl/.venv/lib/python3.8/site-packages/turicreate/extensions.py", line 290, in __run_class_function
    ret = self._tkclass.call_function(fnname, argument_dict)
  File "cy_model.pyx", line 35, in turicreate._cython.cy_model.UnityModel.call_function
  File "cy_model.pyx", line 40, in turicreate._cython.cy_model.UnityModel.call_function
RuntimeError: An error occurred: ValueError: Cannot feed value of shape (2,) for Tensor 'Placeholder_2:0', which has shape '(1,)'
```

**Comment by Vozf** [comment]
It works fine with bs=1

**Comment by TobyRoseman** [comment]
This works fine for me on macOS 10.15 using the [style transfer data from our user guide](https://apple.github.io/turicreate/docs/userguide/style_transfer/).

@Vozf - can you reproduce this issue using that dataset? What operating system are you using?

**Comment by Vozf** [comment]
Ubuntu 20

**Comment by eric573** [comment]
I have this issue as well. My OS info
![Screen Shot 2021-01-23 at 11 36 05 PM](https://user-images.githubusercontent.com/12869470/105624085-c59fd100-5dd3-11eb-9bf1-d870f18b4011.png)
