### ISSUE TITLE
[ERROR] turicreate.toolkits._main: Toolkit error: Column type of target 'rating' must be int or str.

### ISSUE THREAD

**Issue by jchuter** [apple/turicreate#360]
Hi, I am getting this error. 
```
[ERROR] turicreate.toolkits._main: Toolkit error: Column type of target 'rating' must be int or str.
Traceback (most recent call last):
  File "imdb_sent_turi.py", line 45, in <module>
    model = tc.sentence_classifier.create(dataset, 'rating', features=['text'])
  File "/Users/airphoenix/Desktop/aclImdb/sent_turi/lib/python3.6/site-packages/turicreate/toolkits/sentence_classifier/_sentence_classifier.py", line 110, in create
    validation_set=validation_set)
  File "/Users/airphoenix/Desktop/aclImdb/sent_turi/lib/python3.6/site-packages/turicreate/toolkits/classifier/logistic_classifier.py", line 312, in create
    seed=seed)
  File "/Users/airphoenix/Desktop/aclImdb/sent_turi/lib/python3.6/site-packages/turicreate/toolkits/_supervised_learning.py", line 398, in create
    options, verbose)
  File "/Users/airphoenix/Desktop/aclImdb/sent_turi/lib/python3.6/site-packages/turicreate/toolkits/_main.py", line 84, in run
    raise ToolkitError(str(message))
turicreate.toolkits._main.ToolkitError: Column type of target 'rating' must be int or str.
```

My ratings vector is derived from
```or pf in positiveFiles:
    with open(pf, "r") as f:
        indexCounter = 0
        review = f.read()
        split_title = pf.split('_')
        split_title2 = split_title[1].split('.')
        rating = int(split_title2[0])

        ratings_vector.append(rating)
        reviews_vector.append(review)`

```
and is, when printed, an array of ints.
My code for the model is:
```
dataset = {'rating': ratings_vector, 'text': reviews_vector}
model = tc.sentence_classifier.create(dataset, 'rating', features=['text'])
```

**Comment by TobyRoseman** [comment]
@jchuter - Sorry for the unhelpful error message. You need to create a [SFrame](https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.html) and then pass that to `tc.sentence_classifier.create(...)`.

So instead of
`dataset = {'rating': ratings_vector, 'text': reviews_vector}`
do 
`dataset = tc.SFrame({'rating': ratings_vector, 'text': reviews_vector})`

**Comment by jchuter** [comment]
My mistake, and thanks for the response!
