### ISSUE TITLE
String formatting errors

### ISSUE THREAD

**Issue by delirious-lettuce** [apple/turicreate#39]
https://github.com/apple/turicreate/blob/7f07ce795833d0c56c72b3a1fb9339bed6d178d1/src/unity/python/turicreate/cython/cy_pylambda_workers.pyx#L193

```python
# current ^^^
for i in range(n):
    if lcd.input_keys[0][i].size() != n_keys:
        raise ValueError("Row %d does not have the correct number of rows (%d, should be %d)"
                         % (lcd.input_keys[0][i].size(), n))

# the problem is that there are only two arguments provided but the string is expecting three
>>> raise ValueError("Row %d does not have the correct number of rows (%d, should be %d)"
...                  % (22, 44))
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: not enough arguments for format string

# if I am reading this correctly, shouldn't the first argument in the tuple be `i`?
raise ValueError("Row %d does not have the correct number of rows (%d, should be %d)"
                 % (i, lcd.input_keys[0][i].size(), n))
                    ^
                    ^
                    ^
```

---
https://github.com/apple/turicreate/blob/7f07ce795833d0c56c72b3a1fb9339bed6d178d1/src/nnvm/tvm/python/tvm/contrib/xcode.py#L189

```python
>>> rpc_root = 'TEST'
>>> raise RuntimeError("Cannot find tvmrpc.xcodeproj in %s," +
...                    (" please set env TVM_IOS_RPC_ROOT correctly" % rpc_root))
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: not all arguments converted during string formatting

# this error can be fixed by removing two brackets and the `+` sign
>>> raise RuntimeError("Cannot find tvmrpc.xcodeproj in %s,"
...                    " please set env TVM_IOS_RPC_ROOT correctly" % rpc_root)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
RuntimeError: Cannot find tvmrpc.xcodeproj in TEST, please set env TVM_IOS_RPC_ROOT correctly
```

---
https://github.com/apple/turicreate/blob/7f07ce795833d0c56c72b3a1fb9339bed6d178d1/scenario-tests/tests/single_test_driver.py#L11

```python
# current ^^^
def print_help():
    print("""\
{} [sub_directory] [Optional output xunit xml path prefix]

This test runs the scenario test located in the sub directory.
Every python file in the sub directory will be executed against pytest.

Optionally, a setup.py file may exist inside the subdirectory in which case
setup.py is effectively "sourced" before any of the tests are run. This allows
setup.py to modify environment variables which will be picked up by the
tests.

For instance, if the PATH variable is changed in setup.py a different python
environment may be used to run pytest
""" % sys.argv[0])

# the problem above is that the new style `{}` placeholder has been used instead of `%s`
>>> '{}' % 'TEST'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: not all arguments converted during string formatting
>>> '%s' % 'TEST'
'TEST'
>>> '{}'.format('TEST')
'TEST'

# since the project seems to prefer the old style VS new style,
# simply replacing `{}` with `%s` should fix this error
def print_help():
    print("""\
%s [sub_directory] [Optional output xunit xml path prefix]
^^
^^
^^
```

**Comment by hoytak** [comment]
Hi delirious-lettuce,
Great catches -- your fixes are good!  If you could submit a pull request with those fixes, that would be fantastic. 
 
Thanks! 
-- Hoyt

**Comment by delirious-lettuce** [comment]
@hoytak ,

Alright, glad you approve! I was mostly curious about how the first one should be handled but if you are confirming that `i` should be the first argument then I can easily fix all three and send a PR in the next few minutes!
