### ISSUE TITLE
Please use dropna() to drop rows with missing target values.

### ISSUE THREAD

**Issue by alessign** [apple/turicreate#600]
Hi, I have successfully created a model with 22 categories. I have recently added 5 more categories and console is giving me error warning 

`Please use dropna() to drop rows with missing target values.`

I have upgraded Turi Create and coremltools to the latest versions. The full error looks like this:
  

```[16:30:30] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[16:30:30] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Resizing images...
Performing feature extraction on resized images...
Premature end of JPEG file
Completed  512/1883
Completed 1024/1883
Completed 1536/1883
Completed 1883/1883
PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
      You can set "validation_set=None" to disable validation tracking.

[ERROR] turicreate.toolkits._main: Toolkit error: Target column has missing value.                    
Please use dropna() to drop rows with missing target values.
Traceback (most recent call last):
File "train.py", line 8, in <module>
model = tc.image_classifier.create(train_data, target='label', max_iterations=1000)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 132, in create
verbose=verbose)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/turicreate/toolkits/classifier/logistic_classifier.py", line 312, in create
seed=seed)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/turicreate/toolkits/_supervised_learning.py", line 397, in create
options, verbose)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/turicreate/toolkits/_main.py", line 75, in run
raise ToolkitError(str(message))
turicreate.toolkits._main.ToolkitError: Target column has missing value.                   

Please use dropna() to drop rows with missing target values.
```

The code I used is:

**data.py**
```python
import turicreate as tc

image_data = tc.image_analysis.load_images('images', with_path=True)

labels = ['A', 'B', 'C', 'D']

def get_label(path, labels=labels):
  for label in labels:
       if label in path:
           return label

image_data['label'] = image_data['path'].apply(get_label)

#import os
#image_data['label'] = image_data['path'].apply(lambda path:    os.path.dirname(path).split('/')[-1])

image_data.save('boxes.sframe')
image_data.explore()
```

**train.py**
```python
import turicreate as tc

data = tc.SFrame('boxes.sframe')
data.dropna()

train_data, test_data = data.random_split(0.8)

model = tc.image_classifier.create(train_data, target='label',    max_iterations=1000)

predictions = model.classify(test_data)

results = model.evaluate(test_data)

print "Accuracy           : %s" % results['accuracy']
print "Confusion Matrix   : \n%s" % results['confusion_matrix']

model.save('boxes.model')
```

How can I tackle the issue please? Also, do I need to do something about **max_iterations=1000**? I have about 27 folders (categories) to process and each has between 75-130 images...

Thank you for any suggestion

**Comment by srikris** [comment]
It seems like you have `None` values in your path. Your `get_label` function is return `None` values.

**Comment by alessign** [comment]
Hi , thanks for the swift answer! It seems to return values, because I was using the same code previously and it did worked. I only added five new folders with images...

Just now, I have changed the _dat.random_split_ to 0.9 and ran the code again. This time it worked and I was able to export the model. I spent whole day trying to figure this out...again, before it worked perfectly.

Weird...
