### ISSUE TITLE
Crashes while making models on Windows

### ISSUE THREAD

**Issue by AlexChekel1337** [apple/turicreate#605]
I tried turicreate on my MacBook, but it takes so long to process over 1000 images. So I decided to do the same thing on my Windows machine. I installed Ubuntu 18.04 from Windows Store and tried to create the model and then ran into a ton of errors and warnings. So here's my `classifier.py` file:
```
import turicreate as turi

turi.config.set_num_gpus(1)

url = "dataset/"
data = turi.image_analysis.load_images(url)
data["objectType"] = data["path"].apply(lambda path: "Car" if "car" in path else "NotACar")
data.save("car_classifier.sframe")
data.explore()

dataBuffer = turi.SFrame("car_classifier.sframe")
trainingBuffers, testingBuffers = dataBuffer.random_split(0.9)
model = turi.image_classifier.create(trainingBuffers, target="objectType", model="resnet-50", max_iterations=2000)
evaluations = model.evaluate(testingBuffers)
print evaluations["accuracy"]
model.save("car_classifier.model")
model.export_coreml("CarClassifier.mlmodel")
```
And this is the log:
```
alex@DESKTOP-JGJFN39:/mnt/c/UbuntuDocuments/MLClassifier$ python classifier_resnet.py
Read 665 images in 5.00365 secs speed: 132.903 file/sec
Materializing SFrame...
Done.
/home/alex/.local/lib/python2.7/site-packages/turicreate/Turi Create Visualization/visualization_client: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory
[04:33:53] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[04:33:53] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Resizing images...
Performing feature extraction on resized images...
Completed 512/997
Completed 997/997
PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.
WARNING: Detected extremely low variance for feature(s) '__image_features__' because all entries are nearly the same.
Proceeding with model training using all features. If the model does not provide results of adequate quality, exclude the above mentioned feature(s) from the input dataset.
[ERROR] turicreate.toolkits._main: Toolkit error: One-class classification is not currently supported. Please check your target column. If you used data for validation tracking (by default, a 5% split is used), please make sure the training data contains at least 2 classes.

Traceback (most recent call last):
  File "classifier_resnet.py", line 13, in <module>
    model = turi.image_classifier.create(trainingBuffers, target="objectType", model="resnet-50", max_iterations=2000)
  File "/home/alex/.local/lib/python2.7/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 132, in create
    verbose=verbose)
  File "/home/alex/.local/lib/python2.7/site-packages/turicreate/toolkits/classifier/logistic_classifier.py", line 312, in create
    seed=seed)
  File "/home/alex/.local/lib/python2.7/site-packages/turicreate/toolkits/_supervised_learning.py", line 397, in create
    options, verbose)
  File "/home/alex/.local/lib/python2.7/site-packages/turicreate/toolkits/_main.py", line 75, in run
    raise ToolkitError(str(message))
turicreate.toolkits._main.ToolkitError: One-class classification is not currently supported. Please check your target column. If you used data for validation tracking (by default, a 5% split is used), please make sure the training data contains at least 2 classes.
```
Still can't figure out why it says `[ERROR] turicreate.toolkits._main: Toolkit error: One-class classification is not currently supported. Please check your target column. If you used data for validation tracking (by default, a 5% split is used), please make sure the training data contains at least 2 classes.`

**Comment by srikris** [comment]
Seems like your dataset has only 1 class. We can't really classify with only one class.

Can you do the following?

```
trainingBuffers['objectType'].show()
```

and see what the distribution is?

**Comment by AlexChekel1337** [comment]
@srikris my `dataset` folder has `car` and `notacar` so I'm pretty sure that there's actually 2 classes. The same code works just fine on macOS, but gives me a lot of errors on Windows.

**Comment by srikris** [comment]
I think what's going on here is that we are doing an automatic validation set creation which is making 5% of the data as a validation set and for the other 95% you don't have any not-car (or car labels). Do you have a sense for how many cars and not-cars you have?

**Comment by AlexChekel1337** [comment]
@srikris I have ~500 pictures of cars and ~500 pictures of other pictures not related to cars

**Comment by srikris** [comment]
By any chance can you share that dataset for us to repro the bug. I'm not sure why this is happening. It should not be the case.

**Comment by srikris** [comment]
Alternatively, can you paste the output of this?

```
data = turi.image_analysis.load_images(url)
data["objectType"] = data["path"].apply(lambda path: "Car" if "car" in path else "NotACar")
data["objectType"].show()
```

**Comment by AlexChekel1337** [comment]
Here is [repo](https://github.com/AlexChekel1337/turicreate-issue) that I uploaded my `dataset` to.
Here is log: 
```
alex@DESKTOP-JGJFN39:/mnt/c/UbuntuDocuments/MLClassifier$ python classifier_resnet.py
Read 682 images in 5.00884 secs speed: 136.159 file/sec
Materializing SArray...
Done.
Materializing SArray...
Done.
/home/alex/.local/lib/python2.7/site-packages/turicreate/Turi Create Visualization/visualization_client: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory
Materializing SFrame...
Done.
/home/alex/.local/lib/python2.7/site-packages/turicreate/Turi Create Visualization/visualization_client: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory
[05:25:59] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[05:25:59] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Resizing images...
Performing feature extraction on resized images...
Completed 512/980
Completed 980/980
PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.WARNING: Detected extremely low variance for feature(s) '__image_features__' because all entries are nearly the same.
Proceeding with model training using all features. If the model does not provide results of adequate quality, exclude the above mentioned feature(s) from the input dataset.
[ERROR] turicreate.toolkits._main: Toolkit error: One-class classification is not currently supported. Please check your target column. If you used data for validation tracking (by default, a 5% split is used), please make sure the training data contains at least 2 classes.

Traceback (most recent call last):
  File "classifier_resnet.py", line 14, in <module>
    model = turi.image_classifier.create(trainingBuffers, target="objectType", model="resnet-50", max_iterations=2000)
  File "/home/alex/.local/lib/python2.7/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 132, in create
    verbose=verbose)
  File "/home/alex/.local/lib/python2.7/site-packages/turicreate/toolkits/classifier/logistic_classifier.py", line 312, in create
    seed=seed)
  File "/home/alex/.local/lib/python2.7/site-packages/turicreate/toolkits/_supervised_learning.py", line 397, in create
    options, verbose)
  File "/home/alex/.local/lib/python2.7/site-packages/turicreate/toolkits/_main.py", line 75, in run
    raise ToolkitError(str(message))
turicreate.toolkits._main.ToolkitError: One-class classification is not currently supported. Please check your target column. If you used data for validation tracking (by default, a 5% split is used), please make sure the training data contains at least 2 classes.
```
But I can't see any output of `data["objectType"].show()`

**Comment by srikris** [comment]
I'm not sure how this worked before but it seems like a bug in your code.

```
data["objectType"] = data["path"].apply(lambda path: "Car" if "car" in path else "NotACar")
```
that should always return "Car" because "car" is in "car" and "car" is also in "notacar". I'd switch your code to:

```
data["objectType"] = data["path"].apply(lambda path: "NotACar" if "notacar" in path else "Car")
```
I did that and it fixed things. If it did for you, please close it

**Comment by AlexChekel1337** [comment]
@srikris Yeah, that actually helps. Thank you so much!
