### ISSUE TITLE
ImportError: cannot import name libinfo

### ISSUE THREAD

**Issue by johnallen24** [apple/turicreate#706]
I am getting this error when I run my code to create a model. I already tried uninstalling and reinstalling MXNet #311  but the same error appears. 

This is what is shown to me: 
Traceback (most recent call last):
  File "create2.py", line 12, in <module>
    model = tc.object_detector.create(train_data, feature='image', annotations='annotations')
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 145, in create
    from ._mx_detector import YOLOLoss as _YOLOLoss
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/turicreate/toolkits/object_detector/_mx_detector.py", line 9, in <module>
    import mxnet as _mx
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/home/sankhe.ku/anaconda2/envs/venv/lib/python2.7/site-packages/mxnet/base.py", line 30, in <module>
    from . import libinfo
ImportError: cannot import name libinfo

**Comment by TobyRoseman** [comment]
@johnallen24 - What version of mxnet do you have installed and what version of turicreate do you have install? Running the below commands will tell you:
```shell
pip freeze | grep -I mxnet
pip freeze | grep -i turicreate
```
Also what operating system are you using?

**Comment by TobyRoseman** [comment]
@johnallen24 - I'm going to close this issue. Feel free to reopen with the information I requested.

**Comment by nzamosenchuk** [comment]
If you have CUDA9, then you need to downgrade to Cuda 8. (MXNet 1.1.0 for Cuda 9.0 and 9.1 builds are not working properly). If you are running in Google Collaboratory, there is a fix: https://medium.com/@nickzamosenchuk/training-the-model-for-ios-coreml-in-google-colab-60-times-faster-6b3d1669fc46
