### ISSUE TITLE
IG02 Data preparation script for Object Detection throws error

### ISSUE THREAD

**Issue by shantanuchhabra** [apple/turicreate#720]
I downloaded the datasets mentioned [here](https://github.com/apple/turicreate/blob/master/userguide/object_detection/data-preparation.md) 

I then ran the Python script there and got the following error:

```
Traceback (most recent call last):
  File "data-prep.py", line 16, in <module>
    info = info.unpack().rename({'X.0': 'name', 'X.1': 'type'})
  File "/Users/schhabra/Downloads/venv/lib/python2.7/site-packages/turicreate/data_structures/sarray.py", line 3422, in unpack
    raise TypeError("Only SArray of dict/list/array type supports unpack")
TypeError: Only SArray of dict/list/array type supports unpack
```

**Comment by shantanuchhabra** [comment]
This is an error with the way the directory structure is organized when you download the two datasets. Adding documentation to organize files into the right directory structure, will fix this issue.
