### ISSUE TITLE
turicreate import error on macOS 10.12.6 and 

### ISSUE THREAD

**Issue by javacom** [apple/turicreate#816]
### **packages**
pip install turicreate==5.0b2 coremltools==2.0b1

also for turicreate==5.0b1

### **Error**
Traceback (most recent call last):
  File "classifier.py", line 1, in <module>
    import turicreate as turi
  File "/Library/Python/2.7/site-packages/turicreate/__init__.py", line 19, in <module>
    from turicreate.data_structures.sgraph import Vertex, Edge
  File "/Library/Python/2.7/site-packages/turicreate/data_structures/__init__.py", line 18, in <module>
    from . import sframe
  File "/Library/Python/2.7/site-packages/turicreate/data_structures/sframe.py", line 16, in <module>
    from ..connect import main as glconnect
  File "/Library/Python/2.7/site-packages/turicreate/connect/main.py", line 13, in <module>
    from ..cython.cy_unity import UnityGlobalProxy
ImportError: dlopen(/Library/Python/2.7/site-packages/turicreate/cython/cy_unity.so, 2): Symbol not found: _syslog$DARWIN_EXTSN
  Referenced from: /Library/Python/2.7/site-packages/turicreate/cython/../libunity_shared.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Python/2.7/site-packages/turicreate/cython/../libunity_shared.dylib

**Comment by TobyRoseman** [comment]
@javacom - I'm not able to reproduce this issue. When I run `pip install turicreate==5.0b2 coremltools==2.0b1` in a virtual environment, I am able to successfully `import turicreate`. 

This looks like the same issue as #634 which was fixed in 5.0b2. So I would expected you to get this error if you are using 5.0b1 but not 5.0b2. 

Please verify that you are using 5.0b2 by running: `pip freeze | grep turicreate`. Also I would recommend using a virtual environment, as mention in the Installation Section of our [README](https://github.com/apple/turicreate).

If this doesn't resolve your issue, please let us know what operating system version you are using.

**Comment by javacom** [comment]
I am using
macOS Sierra 10.12.6 with all security updates
Xcode 9.2 with command line tools installed
Python 2.7.10
pip 10.0.1
turicreate==5.0b2
coremltools==2.0b1

Should I upgrade to macOS High Sierra in order to use turicreate ?

**Comment by znation** [comment]
@javacom I'll take a look. Upgrading is likely to fix the issue for now, but Turi Create is intended to still run on 10.12 in 5.0. The code that built the 5.0b2 release should work in 10.12, but something may have gone wrong in building or packaging that results in errors when using it in 10.12.
