### ISSUE TITLE
OSError: libcudart.so.8.0 cannot open shared object file. 

### ISSUE THREAD

**Issue by tbass134** [apple/turicreate#935]
im running into a issue when trying to do a style transfer using Ubuntu 16.04
Its a Paperspace machine 
(ML-in-a-box) https://paperspace.zendesk.com/hc/en-us/articles/115002305973-Machine-Learning-in-a-Box

I've install beta5.03 on the machine and using the Style Transfer code

```
import turicreate as tc

styles = tc.load_images('styles/')
content = tc.load_images('content/')
print(content)

model = tc.style_transfer.create(styles,content)
print(model)
test_images = tc.load_images('test/')

stylized_images = model.stylize(test_images)

model.save('mymodel.model')
```

full error is 

(turib3) paperspace@ps88401jf:~/Desktop$ python test.py
+-------------------------------+--------------------------+
|              path             |          image           |
+-------------------------------+--------------------------+
| content/1. pexels-photo-37... |  Height: 350 Width: 558  |
| content/10. tasman-glacier... | Height: 1349 Width: 1080 |
| content/12. landscape_paul... | Height: 640 Width: 1080  |
| content/13. photo-12929919... | Height: 775 Width: 1600  |
|    content/14. the-path.jpg   | Height: 960 Width: 1200  |
|  content/15. dolomites-2.jpg  | Height: 1600 Width: 1068 |
| content/16. pexels-photo-4... |  Height: 350 Width: 684  |
| content/17. landscapes-288... |  Height: 640 Width: 960  |
| content/18. surreal-landsc... | Height: 1400 Width: 2100 |
| content/19. sunset-landsca... | Height: 4000 Width: 6000 |
+-------------------------------+--------------------------+
[18 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    model = tc.style_transfer.create(styles,content)
  File "/home/paperspace/turib3/lib/python3.6/site-packages/turicreate/toolkits/style_transfer/style_transfer.py", line 115, in create
    from ._sframe_loader import SFrameSTIter as _SFrameSTIter
  File "/home/paperspace/turib3/lib/python3.6/site-packages/turicreate/toolkits/style_transfer/_sframe_loader.py", line 11, in <module>
    import mxnet as _mx
  File "/home/paperspace/turib3/lib/python3.6/site-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/home/paperspace/turib3/lib/python3.6/site-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/home/paperspace/turib3/lib/python3.6/site-packages/mxnet/base.py", line 111, in <module>
    _LIB = _load_lib()
  File "/home/paperspace/turib3/lib/python3.6/site-packages/mxnet/base.py", line 103, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/home/paperspace/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory

**Comment by shreyasvj25** [comment]
Hi, you need to install cuda and cudnn. 
Can you follow this: 
https://github.com/apple/turicreate/blob/master/LinuxGPU.md?

**Comment by tbass134** [comment]
Thanks @shreyasvj25 , i've followed those instructions but im still receiving the same error:
